# Site settings
title: 2D Vision
description: 'نقاشی دیجیتال، انیمیشن، گرافیک'
url: 'http://2dvision.com'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: '2DVision'
  email:
  twitter_username: _2dvision
  github_username:
  instagram_username:  _2dvision
  aparat_username:  2dvision

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 5
permalink: /:year/:month/:title/
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
